name: Bug Report
description: Something is not working as intended or approved.
title: "BUG:"
labels: ["work/bug"]
body:

  - type: dropdown
    id: environment
    attributes:
      label: Execution Environment
      description: Where was the bug observed? (use env/hardware if observing robot behavior, otherwise use env/sim)
      options: ["env/sim", "env/hardware"]
    validations:
      required: true

  - type: dropdown
    id: area-selector
    attributes:
      label: Select Primary Area
      description: Choose the label that BEST describes WHERE the work will be focused.
      options:
        - area/auto
        - area/drivetrain
        - area/superstructure
        - area/sensor
        - area/oi
        - area/logic
        - area/infra
        - area/comm
        - area/performance
    validations:
      required: true

  - type: textarea
    id: discrepancy
    attributes:
      label: Approved vs. Observed Behavior
      description: Contrast what was *supposed* to happen with what *actually* happened. Provide sources for approved functionality.
    validations:
      required: true

  - type: checkboxes
    id: signals
    attributes:
      label: Optional Flags
      options:
        - label: Urgent request (signal/needs help)
        - label: Needs more analysis (signal/needs spec)
