name: Feature Request
description: Propose new functionality that has not been implemented.
title: "New Feature:"
labels: ["signal/needs spec"]
body:
  - type: markdown
    attributes:
      value: |
        ### Elaboration Phase
        All new features start in **Elaboration**. Please define the work type and the target area of focus.
  - type: dropdown
    id: work-selector
    attributes:
      label: Select Work Type
      description: Choose the label that BEST describes the work being performed.
      options:
        - work/feature
        - work/tuning
        - work/test
        - work/documentation
    validations:
      required: true

  - type: dropdown
    id: area-selector
    attributes:
      label: Select Primary Area
      description: Choose the label that BEST describes WHERE the work will be focused.
      options:
        - area/auto
        - area/drivetrain
        - area/superstructure
        - area/sensor
        - area/oi
        - area/logic
        - area/infra
        - area/comm
        - area/performance
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: Problem Summary
      description: "As a [role], I want to [action] so that [result]."
      placeholder: "As a driver, I want a button to auto-align to the speaker so that I can score faster."
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment Requirement
      options:
        - This requires access to hardware to complete (env/hardware)
        - This can be completed entirely remote or within a simulation (env/sim)
    validations:
      required: true

  - type: textarea
    id: criteria
    attributes:
      label: Acceptance Criteria
      description: List the conditions that must be true to mark this "Completed."
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
        label: Constraints
        description: Share useful information that must be considered to limit unintentional functionality. Include necessary specifications.

  - type: checkboxes
    id: learn-tags
    attributes:
      label: Learning & Strategy
      options:
        - label: "This is a good task for a Rookie (learn/beginner)"
        - label: "This is a High-Risk task (learn/pair-only)"
        - label: "This is a Prototype (learn/prototype)"
        - label: "Requires deep research (learn/knowledge)"

  - type: checkboxes
    id: add-ons
    attributes:
      label: Additional Tags
      options:
        - label: "This requires extra attention (signal/help wanted)"
