name: Internal Programming Task
description: Maintenance, Refactoring, or Infra (Programming Team Only).
title: "Change: "
body:

  - type: dropdown
    id: work-selector
    attributes:
      label: Select Work Type
      description: Choose the label that BEST describes the work being performed.
      options:
        - work/feature
        - work/tuning
        - work/test
        - work/documentation
    validations:
      required: true

  - type: dropdown
    id: area-selector
    attributes:
      label: Select Primary Area
      description: Choose the label that BEST describes WHERE the work will be focused.
      options:
        - area/auto
        - area/drivetrain
        - area/superstructure
        - area/sensor
        - area/oi
        - area/logic
        - area/infra
        - area/comm
        - area/performance
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Change Summary
